In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
!pip -q install kagglehub

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("terminus7/pokemon-challenge")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Krishna\.cache\kagglehub\datasets\terminus7\pokemon-challenge\versions\1

In [4]:
df=pd.read_csv("pokemon.csv")
df1=pd.read_csv("combats.csv")

In [5]:
# import pandas as pd
# df = pd.read_csv(r"\Users\Krishna\.cache\kagglehub\datasets\terminus7\pokemon-challenge\versions\1\pokemon.csv")
# df.head()

In [6]:
print(path)

C:\Users\Krishna\.cache\kagglehub\datasets\terminus7\pokemon-challenge\versions\1

Let's first inspect the row with the missing 'Name' to understand its context.

In [7]:
df1 = pd.read_csv(r"C:\Users\Krishna\.cache\kagglehub\datasets\terminus7\pokemon-challenge\versions\1/combats.csv")
df1.head()

   First_pokemon  Second_pokemon  Winner
0            266             298     298
1            702             701     701
2            191             668     668
3            237             683     683
4            151             231     151

In [8]:
df.shape

(800, 12)

In [9]:
df1.shape

(50000, 3)

In [10]:
df.drop(['Generation','Legendary'], axis=1, inplace=True)

In [11]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80
4,5,Charmander,Fire,NaN,39,52,43,60,50,65

In [12]:
df = pd.get_dummies(df, columns=['Type 1', 'Type 2'])

In [13]:
df.head()

,#,Name,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Type 1_Bug,Type 1_Dark,...,Type 2_Ghost,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,1,Bulbasaur,45,49,49,65,65,45,False,False,...,False,False,False,False,False,True,False,False,False,False
1,2,Ivysaur,60,62,63,80,80,60,False,False,...,False,False,False,False,False,True,False,False,False,False
2,3,Venusaur,80,82,83,100,100,80,False,False,...,False,False,False,False,False,True,False,False,False,False
3,4,Mega Venusaur,80,100,123,122,120,80,False,False,...,False,False,False,False,False,True,False,False,False,False
4,5,Charmander,39,52,43,60,50,65,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
df.shape

(800, 44)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['Name'].fillna(0, inplace=True)

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
for col in df.columns:
    if col.startswith('Type 1_') or col.startswith('Type 2_'):
        df[col] = df[col].astype(int)

df.head()

,#,Name,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Type 1_Bug,Type 1_Dark,...,Type 2_Ghost,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,1,Bulbasaur,45,49,49,65,65,45,0,0,...,0,0,0,0,0,1,0,0,0,0
1,2,Ivysaur,60,62,63,80,80,60,0,0,...,0,0,0,0,0,1,0,0,0,0
2,3,Venusaur,80,82,83,100,100,80,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Mega Venusaur,80,100,123,122,120,80,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Charmander,39,52,43,60,50,65,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Name'] = le.fit_transform(df['Name'].astype(str))

In [20]:
df.head()

,#,Name,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Type 1_Bug,Type 1_Dark,...,Type 2_Ghost,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,1,69,45,49,49,65,65,45,0,0,...,0,0,0,0,0,1,0,0,0,0
1,2,308,60,62,63,80,80,60,0,0,...,0,0,0,0,0,1,0,0,0,0
2,3,745,80,82,83,100,100,80,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,453,80,100,123,122,120,80,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,88,39,52,43,60,50,65,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
df.columns

Index(['#', 'Name', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed',
       'Type 1_Bug', 'Type 1_Dark', 'Type 1_Dragon', 'Type 1_Electric',
       'Type 1_Fairy', 'Type 1_Fighting', 'Type 1_Fire', 'Type 1_Flying',
       'Type 1_Ghost', 'Type 1_Grass', 'Type 1_Ground', 'Type 1_Ice',
       'Type 1_Normal', 'Type 1_Poison', 'Type 1_Psychic', 'Type 1_Rock',
       'Type 1_Steel', 'Type 1_Water', 'Type 2_Bug', 'Type 2_Dark',
       'Type 2_Dragon', 'Type 2_Electric', 'Type 2_Fairy', 'Type 2_Fighting',
       'Type 2_Fire', 'Type 2_Flying', 'Type 2_Ghost', 'Type 2_Grass',
       'Type 2_Ground', 'Type 2_Ice', 'Type 2_Normal', 'Type 2_Poison',
       'Type 2_Psychic', 'Type 2_Rock', 'Type 2_Steel', 'Type 2_Water'],
      dtype='object')

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']] = sc.fit_transform(df[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']])

In [23]:
df.head()

,#,Name,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Type 1_Bug,Type 1_Dark,...,Type 2_Ghost,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,1,69,-0.950626,-0.924906,-0.797154,-0.239130,-0.248189,-0.801503,0,0,...,0,0,0,0,0,1,0,0,0,0
1,2,308,-0.362822,-0.524130,-0.347917,0.219560,0.291156,-0.285015,0,0,...,0,0,0,0,0,1,0,0,0,0
2,3,745,0.420917,0.092448,0.293849,0.831146,1.010283,0.403635,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,453,0.420917,0.647369,1.577381,1.503891,1.729409,0.403635,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,88,-1.185748,-0.832419,-0.989683,-0.392027,-0.787533,-0.112853,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df1.head()

   First_pokemon  Second_pokemon  Winner
0            266             298     298
1            702             701     701
2            191             668     668
3            237             683     683
4            151             231     151

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df1[['Winner']] = sc.fit_transform(df1[['Winner']])

In [26]:
df1.head()

   First_pokemon  Second_pokemon    Winner
0            266             298 -0.479716
1            702             701  1.263683
2            191             668  1.120923
3            237             683  1.185814
4            151             231 -1.115646

In [27]:
pokemon = pd.read_csv("pokemon.csv")
combats = pd.read_csv("combats.csv")

m1 = combats.merge(pokemon, left_on="First_pokemon", right_on="#", how="left")
m1 = m1.rename(columns={c: f"First_{c}" for c in pokemon.columns if c != "#"}).drop(columns=["#"])

m2 = m1.merge(pokemon, left_on="Second_pokemon", right_on="#", how="left")
m2 = m2.rename(columns={c: f"Second_{c}" for c in pokemon.columns if c != "#"}).drop(columns=["#"])

In [28]:
m2.head()

,First_pokemon,Second_pokemon,Winner,First_Name,First_Type 1,First_Type 2,First_HP,First_Attack,First_Defense,First_Sp. Atk,...,Second_Type 1,Second_Type 2,Second_HP,Second_Attack,Second_Defense,Second_Sp. Atk,Second_Sp. Def,Second_Speed,Second_Generation,Second_Legendary
0,266,298,298,Larvitar,Rock,Ground,50,64,50,45,...,Grass,Dark,70,70,40,60,40,60,3,False
1,702,701,701,Virizion,Grass,Fighting,91,90,72,90,...,Rock,Fighting,91,129,90,72,90,108,5,True
2,191,668,668,Togetic,Fairy,Flying,55,40,85,80,...,Psychic,NaN,75,75,75,125,95,40,5,False
3,237,683,683,Slugma,Fire,NaN,40,40,40,70,...,Dragon,NaN,77,120,90,60,90,48,5,False
4,151,231,151,Omastar,Rock,Water,70,60,125,115,...,Bug,Rock,20,10,230,10,230,5,2,False

In [29]:
y = (m2["Winner"] == m2["First_pokemon"]).astype(int)
print(y.value_counts(normalize=True))

0    0.52798
1    0.47202
Name: proportion, dtype: float64

In [30]:
m2.head()

,First_pokemon,Second_pokemon,Winner,First_Name,First_Type 1,First_Type 2,First_HP,First_Attack,First_Defense,First_Sp. Atk,...,Second_Type 1,Second_Type 2,Second_HP,Second_Attack,Second_Defense,Second_Sp. Atk,Second_Sp. Def,Second_Speed,Second_Generation,Second_Legendary
0,266,298,298,Larvitar,Rock,Ground,50,64,50,45,...,Grass,Dark,70,70,40,60,40,60,3,False
1,702,701,701,Virizion,Grass,Fighting,91,90,72,90,...,Rock,Fighting,91,129,90,72,90,108,5,True
2,191,668,668,Togetic,Fairy,Flying,55,40,85,80,...,Psychic,NaN,75,75,75,125,95,40,5,False
3,237,683,683,Slugma,Fire,NaN,40,40,40,70,...,Dragon,NaN,77,120,90,60,90,48,5,False
4,151,231,151,Omastar,Rock,Water,70,60,125,115,...,Bug,Rock,20,10,230,10,230,5,2,False

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
m2.columns

Index(['First_pokemon', 'Second_pokemon', 'Winner', 'First_Name',
       'First_Type 1', 'First_Type 2', 'First_HP', 'First_Attack',
       'First_Defense', 'First_Sp. Atk', 'First_Sp. Def', 'First_Speed',
       'First_Generation', 'First_Legendary', 'Second_Name', 'Second_Type 1',
       'Second_Type 2', 'Second_HP', 'Second_Attack', 'Second_Defense',
       'Second_Sp. Atk', 'Second_Sp. Def', 'Second_Speed', 'Second_Generation',
       'Second_Legendary'],
      dtype='object')

In [33]:
x = m2[['First_HP','First_Attack','First_Defense','First_Sp. Atk','First_Sp. Def','First_Speed',
        'Second_HP','Second_Attack','Second_Defense','Second_Sp. Atk','Second_Sp. Def','Second_Speed']]

y = (m2['Winner'] == m2['First_pokemon']).astype(int)

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from joblib import dump

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model12 = RandomForestClassifier(n_estimators=100, random_state=42)
model12.fit(x_train, y_train)

print("X features:", x.shape[1])
print("Trained model expects:", model12.n_features_in_)

# overwrite the old file
dump(model12, "model.joblib")
print("✅ Saved NEW model.joblib")
y_pred=model12.predict(x_test)

X features: 12
Trained model expects: 12
✅ Saved NEW model.joblib

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [36]:
acc=accuracy_score(y_test, y_pred)
acc

0.9499

In [37]:
y_p = model12.predict(x_train)

In [38]:
acc = accuracy_score(y_train, y_p)
acc

0.999925

In [39]:
import os
print(os.getcwd())
print(os.listdir())

c:\Users\Krishna\Desktop\POKEMON
['app.py', 'combats.csv', 'model.joblib', 'pokemon.csv', 'POKEMON.ipynb', 'requirements.txt', 'scaler.joblib']

In [40]:
from joblib import load
m = load("model.joblib")
print("Model expects:", m.n_features_in_)

Model expects: 12

In [41]:
y.value_counts(normalize=True)

0    0.52798
1    0.47202
Name: proportion, dtype: float64

In [42]:
print(m2[["Winner", "First_pokemon", "Second_pokemon"]].head(10))
print(m2["Winner"].dtype, m2["First_pokemon"].dtype, m2["Second_pokemon"].dtype)

   Winner  First_pokemon  Second_pokemon
0     298            266             298
1     701            702             701
2     668            191             668
3     683            237             683
4     151            151             231
5     657            657             752
6     134            192             134
7     545             73             545
8     763            220             763
9      31            302              31
int64 int64 int64

In [43]:
print(m2["Winner"].unique())

[298 701 668 683 151 657 134 545 763  31 130 283 269 448 263 240 499 563
 687 441 671 121 649 270 568 767 139 694 549 301 184 536 381 287 406 503
 242 200 376 645 475 737 435 146 715 260 751 424 258 208 646 533 673 141
 244 509 633 595 606 368 746 350 303 115 172  71 610 557 712 451  95 540
 418 276 612  80 535  37 328 159 574 546 229 213 386 732 161 265 603 792
 607 209  40 408 472  47   5 314 195 493 341  63 541 316 398 356 103 600
 445 548 133  51 171 758   6 154 491 271 219 245 588 403 561 119 629 547
 307 153 306  89  32 745 110 537 278 643 165 691 718  42  97 397 483 155
   4  30 340 254 427 496 473 550 785 488 494 129 137 585  57 723 764 708
  23 147 635 158 750 513 264 250 544 517 461 349 226 623 438 523 152 478
 739 684 291 611 560 658 625 524 794 391 592 512  70 347 128 336 490 425
 731 459 421 768 257 302  92 116  69 644 163 164 580 726 420  56 358 532
 534 724 795 432 305 733 428 762 100 771 640 505 614  48 590 431 727   3
 502 714  16 648  20 366 337 198 760  59 127 214  21 404 410 569 249 173
 572 106 525 798  28 247 280  44 442 773 413 679 196 434 716 458 538 702
 136 465  84 521  62 728 246 741 477 284 738 579 713   2 735  67  58  29
 211 615 786 594 586 516 797 317 790   7 469 241 688 476 551 339 709 453
 113 374 784 681 181 498  19 634 567 354 417 704 508 685 463   9 700  73
 216 126 707 692 309 170 299 379 769 690 255 528  24  99 365 409 647 756
 749 248 142 710 233 108 212 120  94 672 327 705 492 149 362 632 670 107
 736 689 277   8 510 282 699 346 323 778 774 375 426 267  72  17 177 192
 443 123 597  65 319 210 480 656 791 617 157  34 300 582 780 581 313  55
 698 132 500 111 519 102 239  13 168 650 393 215 576 335  79 481 695 274
 101 661 631 605 131 179 394 429 174 793 437 150 334 660 348 526 596 531
 430 232 162 742 423 286 686 680 664 234 772  39 383  93 125 570 573 411
 748 598 268  61  52 256 178 343  68 589 166 667 783 355 370 766 677 251
 288 638 719 518 311 522 225 259 148  81 318 527 160 636 296 385 747 583
 182 167 697  85  50 392 654  86 542 752 514 628 613 682 711 599 693 315
 342 332 228 414 765 495 415 674 662 720 124 436 562 138 422 602 467 543
 175 717 369 344  54 642 199 484 156 455 721 295 401 197 703 601 799 616
 787 676 439 364 675 462 266 104 800 359 333 372 202 289 651 757 744 331
  82 730 351 205 204 604  10 759 627 345 559  35 565 367 253 444 626 400
 619 609 637 384 357 729 511 446 326 377 740 440 665 497 223 466 169 539
 552 330 338 281  26 554 520 230 788 388 622 143 191 659 193 109 474 447
 515 412 292 454  27 218 261  87 663 416  18 396  36 273  77  22  75 722
 755 706 387 501  83 145  11 188 361  96 373 206 529 201 203 482 587 304
  76 378 652  53  41  25 186 577  43 135 553 789 608 285 185 105 591 262
  64 324 796 504 310 221 470 666 486  91 380 118 471 272  60 630 485 457
 279 781 407 575 227 696 678 140 450 460 275 297 452 449 725  45 352 114
 194 329 779 506 353 243 734 252 775   1 325 180 653 390 235 433 389 620
 320 584 770 222 507 217 571  98 487 187 621 112  74 360 566 207 530 312
 293 405 555 176 402 382 399 777 776 224 558 371 624 669 238  14 363 294
 122 464  38 308 593 468 564 761 117 489 189 754 290  49 641 395  15 743
 220 753 237  88 578 456 190 639 321]

In [44]:
combats = pd.read_csv("combats.csv")
print(combats["Winner"].head())
print(combats["Winner"].unique()[:10])

0    298
1    701
2    668
3    683
4    151
Name: Winner, dtype: int64
[298 701 668 683 151 657 134 545 763  31]

In [45]:
# check raw combats file (the source)
combats = df1  # assuming df1 is your combats dataframe
print("combats columns:", combats.columns.tolist())
print("combats Winner unique:", combats["Winner"].unique()[:20])

# after your merges: what does m2 contain for winner & pokes?
print("m2 Winner unique:", m2["Winner"].unique()[:20])
print(m2[["Winner","First_pokemon","Second_pokemon"]].head(10))

combats columns: ['First_pokemon', 'Second_pokemon', 'Winner']
combats Winner unique: [-0.47971633  1.2636826   1.12092289  1.18581367 -1.11564597  1.07333632
 -1.18918885  0.5888185   1.53189782 -1.6347722  -1.20649306 -0.54460711
 -0.60517184  0.16919146 -0.63112815 -0.73062735  0.38982011  0.66668743
  1.20311787  0.1389091 ]
m2 Winner unique: [298 701 668 683 151 657 134 545 763  31 130 283 269 448 263 240 499 563
 687 441]
   Winner  First_pokemon  Second_pokemon
0     298            266             298
1     701            702             701
2     668            191             668
3     683            237             683
4     151            151             231
5     657            657             752
6     134            192             134
7     545             73             545
8     763            220             763
9      31            302              31

In [46]:
print(combats[["First_pokemon","Second_pokemon","Winner"]].head())
print(combats["Winner"].dtype)
print(combats["Winner"].unique()[:10])

   First_pokemon  Second_pokemon    Winner
0            266             298 -0.479716
1            702             701  1.263683
2            191             668  1.120923
3            237             683  1.185814
4            151             231 -1.115646
float64
[-0.47971633  1.2636826   1.12092289  1.18581367 -1.11564597  1.07333632
 -1.18918885  0.5888185   1.53189782 -1.6347722 ]